/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_proxy.h"
#include <fcntl.h>
#include <unistd.h> // read/write fd
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>

// proxy support https only
#define HTTPS 0

#define STOP_SIG -1
#define PORT 5000

#define P_DEBUG 1

#define SA struct sockaddr

int sockfd;

int string_2_num(char *str); // tool func
int parse_head(dest_host *dh, int fd); // DNS and PORT capture
int open_server(struct sockaddr_in *servaddr, int saddr_s, struct sockaddr_in* cli, int caddr_s, int *sockfd);
void close_socket(){
	close(sockfd);
}

void
rpc_proxy_program_1(char *host)
{
	CLIENT *clnt;
	struct sockaddr_in seraddr, cli;

#ifndef	DEBUG
	clnt = clnt_create (host, rpc_proxy_program, rpc_proxy_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// open server for incoming client
	int client = open_server(&seraddr, sizeof(seraddr), &cli, sizeof(cli), &sockfd);

	// connect proxy to destination
	dest_host dh;
	if(parse_head(&dh, client) != HTTPS){
		printf("Support HTTPS Proxy mozilla protocol only\n");
		clnt_destroy (clnt);
		return;
	}
	int *fd = connect_proxy_1(&dh, clnt);
	if (fd == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		clnt_destroy (clnt);
		return;
	}

	if (*fd == -1){
		printf("connection fail\n");
		clnt_destroy (clnt);
		return;
	}

	// setup non-blocking r/w
	// int flags = fcntl(client, F_GETFL, 0);
	// fcntl(client, F_SETFL, flags | O_NONBLOCK);
	// flags = fcntl(1, F_GETFD, 0);
	// fcntl(1, F_SETFL, flags | O_NONBLOCK);

	// flush another header
	// char c;
	// while(read(client, &c, 1) > 0){;}
  
	write(client, "HTTP/1.1 200 OK\r\n\r\n", 23); // response to client

	char data[100]; // data transfer of proxy

	// transfer data
	p_message message;
	message.ct = data;
	message.fd = *fd;
	while(fd){
		// send message from src to dest
		message.length = read(client, message.ct, sizeof(data));
		if(message.length > 0){
			int *result_send = send_proxy_1(&message, clnt);
			
			if (result_send == (int *) NULL) {
				clnt_perror (clnt, "call failed");
				break;
			}

			if(*result_send == STOP_SIG){
				printf("Stop signal from dest\n");
				break;
			}
		}

		// recv message from dest to src
		p_message *result_recv = recv_proxy_1(fd, clnt);
		
		if (result_recv == (p_message *) NULL) {
			clnt_perror (clnt, "call failed");
			break;
		}
		
		if(result_recv->length > 0){
			int value = write(client, result_recv->ct, result_recv->length);
			if(value == STOP_SIG){
				break;
			}
		}
	}

	close_proxy_1(fd, clnt); // stop connection
	close(sockfd);
	close(client);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	// called when terminate
	signal(SIGINT, close_socket);

	rpc_proxy_program_1 (host);
}

int parse_head(dest_host *dh, int fd){
	char line[500];
	int mode = -1;
	
	// debug mode
	if(P_DEBUG){
		int value = read(fd, line, sizeof(line));
		line[value] = '\0';
		printf("connect method length: %d\n", value);
		printf("connect data: %s", line);
	}

	if(strncmp(line, "CONNECT", 7) == 0){
		// https ver
		for(int i = 0; i < strlen(line); i++){
			if(line[i] == ' '){
				int index = 0;
				char ip_addr[100];
				
				// get DNS name
				while(line[++i] != ':'){
					ip_addr[index++] = line[i];
				}
				ip_addr[index] = '\0';
				dh->host = (char*) malloc (strlen(ip_addr) + 1);
				memcpy(dh->host, ip_addr, strlen(ip_addr) + 1);

				// get port
				index = 0;
				while(line[++i] != ' '){
					ip_addr[index++] = line[i];
				}
				ip_addr[index] = '\0';
				dh->port = string_2_num(ip_addr);
				mode = HTTPS;
				break;
			}
		}
	}
	return mode;
}

int string_2_num(char *str){
	int num = 0;
	for(int i = 0; i < strlen(str); i++){
		num = num * 10 + (str[i] - '0');
	}
	return num;
}

int open_server(struct sockaddr_in *servaddr, int saddr_s, struct sockaddr_in* cli, int caddr_s, int *sockfd){
	*sockfd = socket(AF_INET, SOCK_STREAM, 0);
	if (*sockfd == -1) { 
        printf("socket creation failed...\n"); 
        exit(0); 
    } 
    else
        printf("Socket successfully created..\n"); 
    bzero(servaddr, saddr_s);
  
    // assign IP, PORT 
    servaddr->sin_family = AF_INET; 
    servaddr->sin_addr.s_addr = htonl(INADDR_ANY); 
    servaddr->sin_port = htons(PORT); 
  
    // Binding newly created socket to given IP and verification 
    if ((bind(*sockfd, (SA*)servaddr, saddr_s)) != 0) { 
        printf("socket bind failed...\n"); 
        exit(0); 
    } 
    else
        printf("Socket successfully binded..\n"); 
  
    // Now server is ready to listen and verification 
    if ((listen(*sockfd, 1)) != 0) { 
        printf("Listen failed...\n"); 
        exit(0); 
    } 
    else
        printf("Server listening..\n");

		int len = caddr_s;
  
    // Accept the data packet from client and verification 
    int connfd = accept(*sockfd, (SA*)cli, &len); 
    if (connfd < 0) { 
        printf("server acccept failed...\n"); 
        exit(0); 
    } 
    else
        printf("server acccept the client...\n");
		
		return connfd;
}

