/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_proxy.h"


void
rpc_proxy_program_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	dest_host  connect_proxy_1_arg;
	int  *result_2;
	p_message  send_proxy_1_arg;
	int  *result_3;
	p_message  recv_proxy_1_arg;
	int  *result_4;
	int  close_proxy_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, rpc_proxy_program, rpc_proxy_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = connect_proxy_1(&connect_proxy_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = send_proxy_1(&send_proxy_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = recv_proxy_1(&recv_proxy_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = close_proxy_1(&close_proxy_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_proxy_program_1 (host);
exit (0);
}
